export type FoodCategory =
  | "vegetable"
  | "fruit"
  | "protein"
  | "grain"
  | "dairy"
  | "snack"
  | "spice"
  | "drink";

export type Food = {
  id: string;
  name: string;
  emoji: string;
  category: FoodCategory;
};

/* Curated kid-oriented food catalog used by the taste test (~300 items
   across 8 categories). Ordered: original v0 ten first, then alphabetically
   inside each category. Slugs are stable IDs — never rename a slug; if a
   food needs to be removed, leave it in place rather than orphan ratings. */
export const FOODS: Food[] = [
  /* --- Original v0 ten (preserve IDs for existing ratings) --- */
  { id: "carrot", name: "Carrot", emoji: "🥕", category: "vegetable" },
  { id: "broccoli", name: "Broccoli", emoji: "🥦", category: "vegetable" },
  { id: "cucumber", name: "Cucumber", emoji: "🥒", category: "vegetable" },
  { id: "sweet-potato", name: "Sweet potato", emoji: "🍠", category: "vegetable" },
  { id: "spinach", name: "Spinach", emoji: "🥬", category: "vegetable" },
  { id: "strawberry", name: "Strawberry", emoji: "🍓", category: "fruit" },
  { id: "banana", name: "Banana", emoji: "🍌", category: "fruit" },
  { id: "apple", name: "Apple", emoji: "🍎", category: "fruit" },
  { id: "egg", name: "Scrambled egg", emoji: "🥚", category: "protein" },
  { id: "chicken", name: "Roast chicken", emoji: "🍗", category: "protein" },

  /* --- Vegetables (50 more) --- */
  { id: "arugula", name: "Arugula", emoji: "🥬", category: "vegetable" },
  { id: "artichoke", name: "Artichoke", emoji: "🌿", category: "vegetable" },
  { id: "asparagus", name: "Asparagus", emoji: "🌿", category: "vegetable" },
  { id: "bamboo-shoots", name: "Bamboo shoots", emoji: "🌿", category: "vegetable" },
  { id: "beet", name: "Beet", emoji: "🟣", category: "vegetable" },
  { id: "bell-pepper", name: "Bell pepper", emoji: "🫑", category: "vegetable" },
  { id: "bok-choy", name: "Bok choy", emoji: "🥬", category: "vegetable" },
  { id: "brussels-sprouts", name: "Brussels sprouts", emoji: "🥬", category: "vegetable" },
  { id: "butternut-squash", name: "Butternut squash", emoji: "🎃", category: "vegetable" },
  { id: "cabbage", name: "Cabbage", emoji: "🥬", category: "vegetable" },
  { id: "cassava", name: "Cassava", emoji: "🥔", category: "vegetable" },
  { id: "cauliflower", name: "Cauliflower", emoji: "🥦", category: "vegetable" },
  { id: "celery", name: "Celery", emoji: "🌿", category: "vegetable" },
  { id: "cherry-tomato", name: "Cherry tomato", emoji: "🍅", category: "vegetable" },
  { id: "collard-greens", name: "Collard greens", emoji: "🥬", category: "vegetable" },
  { id: "corn", name: "Corn", emoji: "🌽", category: "vegetable" },
  { id: "daikon", name: "Daikon", emoji: "🌿", category: "vegetable" },
  { id: "edamame", name: "Edamame", emoji: "🟢", category: "vegetable" },
  { id: "eggplant", name: "Eggplant", emoji: "🍆", category: "vegetable" },
  { id: "endive", name: "Endive", emoji: "🥬", category: "vegetable" },
  { id: "fennel", name: "Fennel", emoji: "🌿", category: "vegetable" },
  { id: "garlic", name: "Garlic", emoji: "🧄", category: "vegetable" },
  { id: "ginger-root", name: "Ginger root", emoji: "🫚", category: "vegetable" },
  { id: "green-beans", name: "Green beans", emoji: "🟢", category: "vegetable" },
  { id: "iceberg", name: "Iceberg lettuce", emoji: "🥬", category: "vegetable" },
  { id: "jicama", name: "Jicama", emoji: "🥔", category: "vegetable" },
  { id: "kale", name: "Kale", emoji: "🥬", category: "vegetable" },
  { id: "kohlrabi", name: "Kohlrabi", emoji: "🥬", category: "vegetable" },
  { id: "leek", name: "Leek", emoji: "🧅", category: "vegetable" },
  { id: "lettuce", name: "Lettuce", emoji: "🥗", category: "vegetable" },
  { id: "mushroom", name: "Mushroom", emoji: "🍄", category: "vegetable" },
  { id: "okra", name: "Okra", emoji: "🌿", category: "vegetable" },
  { id: "onion", name: "Onion", emoji: "🧅", category: "vegetable" },
  { id: "parsnip", name: "Parsnip", emoji: "🥕", category: "vegetable" },
  { id: "peas", name: "Peas", emoji: "🟢", category: "vegetable" },
  { id: "plantain", name: "Plantain", emoji: "🍌", category: "vegetable" },
  { id: "portobello", name: "Portobello", emoji: "🍄", category: "vegetable" },
  { id: "potato", name: "Potato", emoji: "🥔", category: "vegetable" },
  { id: "pumpkin", name: "Pumpkin", emoji: "🎃", category: "vegetable" },
  { id: "radish", name: "Radish", emoji: "🌶️", category: "vegetable" },
  { id: "romaine", name: "Romaine", emoji: "🥬", category: "vegetable" },
  { id: "scallion", name: "Scallion", emoji: "🌿", category: "vegetable" },
  { id: "snap-peas", name: "Snap peas", emoji: "🟢", category: "vegetable" },
  { id: "snow-peas", name: "Snow peas", emoji: "🟢", category: "vegetable" },
  { id: "sprouts", name: "Sprouts", emoji: "🌱", category: "vegetable" },
  { id: "swiss-chard", name: "Swiss chard", emoji: "🥬", category: "vegetable" },
  { id: "taro", name: "Taro", emoji: "🥔", category: "vegetable" },
  { id: "tomato", name: "Tomato", emoji: "🍅", category: "vegetable" },
  { id: "turnip", name: "Turnip", emoji: "🥬", category: "vegetable" },
  { id: "watercress", name: "Watercress", emoji: "🥬", category: "vegetable" },
  { id: "yam", name: "Yam", emoji: "🍠", category: "vegetable" },
  { id: "zucchini", name: "Zucchini", emoji: "🥒", category: "vegetable" },
  { id: "napa-cabbage", name: "Napa cabbage", emoji: "🥬", category: "vegetable" },
  { id: "chayote", name: "Chayote", emoji: "🌿", category: "vegetable" },
  { id: "watermelon-radish", name: "Watermelon radish", emoji: "🌶️", category: "vegetable" },

  /* --- Fruits (47 more) --- */
  { id: "apricot", name: "Apricot", emoji: "🍑", category: "fruit" },
  { id: "avocado", name: "Avocado", emoji: "🥑", category: "fruit" },
  { id: "blackberry", name: "Blackberry", emoji: "🫐", category: "fruit" },
  { id: "blueberry", name: "Blueberry", emoji: "🫐", category: "fruit" },
  { id: "cantaloupe", name: "Cantaloupe", emoji: "🍈", category: "fruit" },
  { id: "cherry", name: "Cherry", emoji: "🍒", category: "fruit" },
  { id: "clementine", name: "Clementine", emoji: "🍊", category: "fruit" },
  { id: "coconut", name: "Coconut", emoji: "🥥", category: "fruit" },
  { id: "cranberry", name: "Cranberry", emoji: "🔴", category: "fruit" },
  { id: "currant", name: "Currant", emoji: "🔴", category: "fruit" },
  { id: "date", name: "Date", emoji: "🟤", category: "fruit" },
  { id: "dragon-fruit", name: "Dragon fruit", emoji: "🍎", category: "fruit" },
  { id: "dried-apricot", name: "Dried apricot", emoji: "🟠", category: "fruit" },
  { id: "dried-mango", name: "Dried mango", emoji: "🟠", category: "fruit" },
  { id: "fig", name: "Fig", emoji: "🟣", category: "fruit" },
  { id: "gooseberry", name: "Gooseberry", emoji: "🟢", category: "fruit" },
  { id: "grape", name: "Grape", emoji: "🍇", category: "fruit" },
  { id: "grapefruit", name: "Grapefruit", emoji: "🍊", category: "fruit" },
  { id: "guava", name: "Guava", emoji: "🍐", category: "fruit" },
  { id: "honeydew", name: "Honeydew", emoji: "🍈", category: "fruit" },
  { id: "kiwi", name: "Kiwi", emoji: "🥝", category: "fruit" },
  { id: "lemon", name: "Lemon", emoji: "🍋", category: "fruit" },
  { id: "lime", name: "Lime", emoji: "🟢", category: "fruit" },
  { id: "lychee", name: "Lychee", emoji: "🟡", category: "fruit" },
  { id: "mandarin", name: "Mandarin", emoji: "🍊", category: "fruit" },
  { id: "mango", name: "Mango", emoji: "🥭", category: "fruit" },
  { id: "melon", name: "Melon", emoji: "🍈", category: "fruit" },
  { id: "mulberry", name: "Mulberry", emoji: "🟣", category: "fruit" },
  { id: "nectarine", name: "Nectarine", emoji: "🍑", category: "fruit" },
  { id: "olive", name: "Olive", emoji: "🫒", category: "fruit" },
  { id: "orange", name: "Orange", emoji: "🍊", category: "fruit" },
  { id: "papaya", name: "Papaya", emoji: "🥭", category: "fruit" },
  { id: "passion-fruit", name: "Passion fruit", emoji: "🥭", category: "fruit" },
  { id: "peach", name: "Peach", emoji: "🍑", category: "fruit" },
  { id: "pear", name: "Pear", emoji: "🍐", category: "fruit" },
  { id: "persimmon", name: "Persimmon", emoji: "🍑", category: "fruit" },
  { id: "pineapple", name: "Pineapple", emoji: "🍍", category: "fruit" },
  { id: "plum", name: "Plum", emoji: "🍑", category: "fruit" },
  { id: "pomegranate", name: "Pomegranate", emoji: "🍎", category: "fruit" },
  { id: "prune", name: "Prune", emoji: "🟤", category: "fruit" },
  { id: "raisin", name: "Raisin", emoji: "🟤", category: "fruit" },
  { id: "raspberry", name: "Raspberry", emoji: "🍓", category: "fruit" },
  { id: "rhubarb", name: "Rhubarb", emoji: "🌿", category: "fruit" },
  { id: "starfruit", name: "Starfruit", emoji: "⭐", category: "fruit" },
  { id: "tangerine", name: "Tangerine", emoji: "🍊", category: "fruit" },
  { id: "watermelon", name: "Watermelon", emoji: "🍉", category: "fruit" },
  { id: "banana-chip", name: "Banana chip", emoji: "🍌", category: "fruit" },

  /* --- Proteins (38 more) --- */
  { id: "almond-butter", name: "Almond butter", emoji: "🟤", category: "protein" },
  { id: "almonds", name: "Almonds", emoji: "🥜", category: "protein" },
  { id: "anchovy", name: "Anchovy", emoji: "🐟", category: "protein" },
  { id: "bacon", name: "Bacon", emoji: "🥓", category: "protein" },
  { id: "beef", name: "Beef", emoji: "🥩", category: "protein" },
  { id: "black-bean", name: "Black bean", emoji: "⚫", category: "protein" },
  { id: "cashews", name: "Cashews", emoji: "🥜", category: "protein" },
  { id: "chickpea", name: "Chickpea", emoji: "🟡", category: "protein" },
  { id: "clam", name: "Clam", emoji: "🦪", category: "protein" },
  { id: "cod", name: "Cod", emoji: "🐟", category: "protein" },
  { id: "crab", name: "Crab", emoji: "🦀", category: "protein" },
  { id: "ham", name: "Ham", emoji: "🍖", category: "protein" },
  { id: "hummus", name: "Hummus", emoji: "🟡", category: "protein" },
  { id: "kidney-bean", name: "Kidney bean", emoji: "🔴", category: "protein" },
  { id: "lentil", name: "Lentil", emoji: "🟤", category: "protein" },
  { id: "lima-bean", name: "Lima bean", emoji: "🟢", category: "protein" },
  { id: "lobster", name: "Lobster", emoji: "🦞", category: "protein" },
  { id: "mussel", name: "Mussel", emoji: "🦪", category: "protein" },
  { id: "navy-bean", name: "Navy bean", emoji: "⚪", category: "protein" },
  { id: "oyster", name: "Oyster", emoji: "🦪", category: "protein" },
  { id: "peanut-butter", name: "Peanut butter", emoji: "🟤", category: "protein" },
  { id: "peanuts", name: "Peanuts", emoji: "🥜", category: "protein" },
  { id: "pinto-bean", name: "Pinto bean", emoji: "🟤", category: "protein" },
  { id: "pork", name: "Pork", emoji: "🥓", category: "protein" },
  { id: "salmon", name: "Salmon", emoji: "🐟", category: "protein" },
  { id: "sardine", name: "Sardine", emoji: "🐟", category: "protein" },
  { id: "sausage", name: "Sausage", emoji: "🌭", category: "protein" },
  { id: "scallop", name: "Scallop", emoji: "🐚", category: "protein" },
  { id: "seitan", name: "Seitan", emoji: "🍞", category: "protein" },
  { id: "shrimp", name: "Shrimp", emoji: "🦐", category: "protein" },
  { id: "soy-protein", name: "Soy protein", emoji: "🟡", category: "protein" },
  { id: "tempeh", name: "Tempeh", emoji: "🍲", category: "protein" },
  { id: "tofu", name: "Tofu", emoji: "🍲", category: "protein" },
  { id: "tuna", name: "Tuna", emoji: "🐟", category: "protein" },
  { id: "turkey", name: "Turkey", emoji: "🦃", category: "protein" },
  { id: "walnuts", name: "Walnuts", emoji: "🌰", category: "protein" },
  { id: "white-bean", name: "White bean", emoji: "⚪", category: "protein" },
  { id: "hard-boiled-egg", name: "Hard-boiled egg", emoji: "🥚", category: "protein" },

  /* --- Grains (35) --- */
  { id: "bagel", name: "Bagel", emoji: "🥯", category: "grain" },
  { id: "baguette", name: "Baguette", emoji: "🥖", category: "grain" },
  { id: "barley", name: "Barley", emoji: "🌾", category: "grain" },
  { id: "basmati-rice", name: "Basmati rice", emoji: "🍚", category: "grain" },
  { id: "bread", name: "Bread", emoji: "🍞", category: "grain" },
  { id: "brown-rice", name: "Brown rice", emoji: "🍚", category: "grain" },
  { id: "buckwheat", name: "Buckwheat", emoji: "🌾", category: "grain" },
  { id: "bulgur", name: "Bulgur", emoji: "🌾", category: "grain" },
  { id: "cornbread", name: "Cornbread", emoji: "🌽", category: "grain" },
  { id: "couscous", name: "Couscous", emoji: "🌾", category: "grain" },
  { id: "farro", name: "Farro", emoji: "🌾", category: "grain" },
  { id: "gnocchi", name: "Gnocchi", emoji: "🍝", category: "grain" },
  { id: "granola", name: "Granola", emoji: "🥣", category: "grain" },
  { id: "jasmine-rice", name: "Jasmine rice", emoji: "🍚", category: "grain" },
  { id: "lasagna", name: "Lasagna", emoji: "🍝", category: "grain" },
  { id: "macaroni", name: "Macaroni", emoji: "🍝", category: "grain" },
  { id: "millet", name: "Millet", emoji: "🌾", category: "grain" },
  { id: "muesli", name: "Muesli", emoji: "🥣", category: "grain" },
  { id: "naan", name: "Naan", emoji: "🫓", category: "grain" },
  { id: "oat", name: "Oats", emoji: "🌾", category: "grain" },
  { id: "oatmeal", name: "Oatmeal", emoji: "🥣", category: "grain" },
  { id: "pasta", name: "Pasta", emoji: "🍝", category: "grain" },
  { id: "penne", name: "Penne", emoji: "🍝", category: "grain" },
  { id: "pita", name: "Pita", emoji: "🫓", category: "grain" },
  { id: "polenta", name: "Polenta", emoji: "🌽", category: "grain" },
  { id: "quinoa", name: "Quinoa", emoji: "🌾", category: "grain" },
  { id: "ramen", name: "Ramen", emoji: "🍜", category: "grain" },
  { id: "ravioli", name: "Ravioli", emoji: "🥟", category: "grain" },
  { id: "rice", name: "White rice", emoji: "🍚", category: "grain" },
  { id: "soba", name: "Soba", emoji: "🍜", category: "grain" },
  { id: "sourdough", name: "Sourdough", emoji: "🍞", category: "grain" },
  { id: "spaghetti", name: "Spaghetti", emoji: "🍝", category: "grain" },
  { id: "tortilla", name: "Tortilla", emoji: "🫓", category: "grain" },
  { id: "udon", name: "Udon", emoji: "🍜", category: "grain" },
  { id: "wild-rice", name: "Wild rice", emoji: "🍚", category: "grain" },

  /* --- Dairy (25) --- */
  { id: "almond-milk", name: "Almond milk", emoji: "🥛", category: "dairy" },
  { id: "brie", name: "Brie", emoji: "🧀", category: "dairy" },
  { id: "butter", name: "Butter", emoji: "🧈", category: "dairy" },
  { id: "cheddar", name: "Cheddar", emoji: "🧀", category: "dairy" },
  { id: "cottage-cheese", name: "Cottage cheese", emoji: "🧀", category: "dairy" },
  { id: "cream", name: "Cream", emoji: "🥛", category: "dairy" },
  { id: "cream-cheese", name: "Cream cheese", emoji: "🧀", category: "dairy" },
  { id: "feta", name: "Feta", emoji: "🧀", category: "dairy" },
  { id: "ghee", name: "Ghee", emoji: "🧈", category: "dairy" },
  { id: "goat-cheese", name: "Goat cheese", emoji: "🧀", category: "dairy" },
  { id: "greek-yogurt", name: "Greek yogurt", emoji: "🥛", category: "dairy" },
  { id: "ice-cream", name: "Ice cream", emoji: "🍦", category: "dairy" },
  { id: "kefir", name: "Kefir", emoji: "🥛", category: "dairy" },
  { id: "milk", name: "Milk", emoji: "🥛", category: "dairy" },
  { id: "mozzarella", name: "Mozzarella", emoji: "🧀", category: "dairy" },
  { id: "oat-milk", name: "Oat milk", emoji: "🥛", category: "dairy" },
  { id: "parmesan", name: "Parmesan", emoji: "🧀", category: "dairy" },
  { id: "ricotta", name: "Ricotta", emoji: "🧀", category: "dairy" },
  { id: "skim-milk", name: "Skim milk", emoji: "🥛", category: "dairy" },
  { id: "skyr", name: "Skyr", emoji: "🥛", category: "dairy" },
  { id: "sour-cream", name: "Sour cream", emoji: "🥛", category: "dairy" },
  { id: "soy-milk", name: "Soy milk", emoji: "🥛", category: "dairy" },
  { id: "swiss-cheese", name: "Swiss cheese", emoji: "🧀", category: "dairy" },
  { id: "whole-milk", name: "Whole milk", emoji: "🥛", category: "dairy" },
  { id: "yogurt", name: "Yogurt", emoji: "🥛", category: "dairy" },

  /* --- Snacks (30) --- */
  { id: "animal-crackers", name: "Animal crackers", emoji: "🐻", category: "snack" },
  { id: "applesauce", name: "Applesauce", emoji: "🍎", category: "snack" },
  { id: "cheese-cracker", name: "Cheese cracker", emoji: "🧀", category: "snack" },
  { id: "cheese-stick", name: "Cheese stick", emoji: "🧀", category: "snack" },
  { id: "chips", name: "Chips", emoji: "🍟", category: "snack" },
  { id: "crackers", name: "Crackers", emoji: "🍘", category: "snack" },
  { id: "dried-fruit-mix", name: "Dried fruit mix", emoji: "🍎", category: "snack" },
  { id: "energy-bar", name: "Energy bar", emoji: "🍫", category: "snack" },
  { id: "fig-bar", name: "Fig bar", emoji: "🍪", category: "snack" },
  { id: "fruit-bar", name: "Fruit bar", emoji: "🍓", category: "snack" },
  { id: "fruit-leather", name: "Fruit leather", emoji: "🍓", category: "snack" },
  { id: "fruit-snack", name: "Fruit snack", emoji: "🍓", category: "snack" },
  { id: "graham-cracker", name: "Graham cracker", emoji: "🍪", category: "snack" },
  { id: "granola-bar", name: "Granola bar", emoji: "🍫", category: "snack" },
  { id: "gummy-bears", name: "Gummy bears", emoji: "🐻", category: "snack" },
  { id: "hummus-cup", name: "Hummus cup", emoji: "🟡", category: "snack" },
  { id: "jerky", name: "Jerky", emoji: "🥩", category: "snack" },
  { id: "nut-butter-pouch", name: "Nut-butter pouch", emoji: "🟤", category: "snack" },
  { id: "oatmeal-cookie", name: "Oatmeal cookie", emoji: "🍪", category: "snack" },
  { id: "pita-chips", name: "Pita chips", emoji: "🍞", category: "snack" },
  { id: "popcorn", name: "Popcorn", emoji: "🍿", category: "snack" },
  { id: "pretzels", name: "Pretzels", emoji: "🥨", category: "snack" },
  { id: "rice-cakes", name: "Rice cakes", emoji: "🍘", category: "snack" },
  { id: "rice-crispy-treat", name: "Rice crispy treat", emoji: "🍙", category: "snack" },
  { id: "smoothie-pop", name: "Smoothie pop", emoji: "🍡", category: "snack" },
  { id: "tortilla-chips", name: "Tortilla chips", emoji: "🍟", category: "snack" },
  { id: "trail-mix", name: "Trail mix", emoji: "🥜", category: "snack" },
  { id: "vanilla-wafer", name: "Vanilla wafer", emoji: "🍪", category: "snack" },
  { id: "veggie-stick", name: "Veggie stick", emoji: "🌿", category: "snack" },
  { id: "yogurt-pouch", name: "Yogurt pouch", emoji: "🥛", category: "snack" },

  /* --- Spices & seasonings (30) --- */
  { id: "basil", name: "Basil", emoji: "🌿", category: "spice" },
  { id: "bay-leaf", name: "Bay leaf", emoji: "🌿", category: "spice" },
  { id: "cardamom", name: "Cardamom", emoji: "🟢", category: "spice" },
  { id: "chives", name: "Chives", emoji: "🌿", category: "spice" },
  { id: "cilantro", name: "Cilantro", emoji: "🌿", category: "spice" },
  { id: "cinnamon", name: "Cinnamon", emoji: "🟤", category: "spice" },
  { id: "cloves", name: "Cloves", emoji: "🟤", category: "spice" },
  { id: "cumin", name: "Cumin", emoji: "🌿", category: "spice" },
  { id: "dill", name: "Dill", emoji: "🌿", category: "spice" },
  { id: "garlic-powder", name: "Garlic powder", emoji: "🧄", category: "spice" },
  { id: "ginger-spice", name: "Ginger (spice)", emoji: "🫚", category: "spice" },
  { id: "honey", name: "Honey", emoji: "🍯", category: "spice" },
  { id: "ketchup", name: "Ketchup", emoji: "🟥", category: "spice" },
  { id: "maple-syrup", name: "Maple syrup", emoji: "🍯", category: "spice" },
  { id: "mint", name: "Mint", emoji: "🌿", category: "spice" },
  { id: "mustard", name: "Mustard", emoji: "🟡", category: "spice" },
  { id: "nutmeg", name: "Nutmeg", emoji: "🟤", category: "spice" },
  { id: "onion-powder", name: "Onion powder", emoji: "🧅", category: "spice" },
  { id: "oregano", name: "Oregano", emoji: "🌿", category: "spice" },
  { id: "paprika", name: "Paprika", emoji: "🌶️", category: "spice" },
  { id: "parsley", name: "Parsley", emoji: "🌿", category: "spice" },
  { id: "pepper", name: "Black pepper", emoji: "🌶️", category: "spice" },
  { id: "rosemary", name: "Rosemary", emoji: "🌿", category: "spice" },
  { id: "sage-herb", name: "Sage", emoji: "🌿", category: "spice" },
  { id: "salt", name: "Salt", emoji: "🧂", category: "spice" },
  { id: "soy-sauce", name: "Soy sauce", emoji: "🟤", category: "spice" },
  { id: "thyme", name: "Thyme", emoji: "🌿", category: "spice" },
  { id: "turmeric", name: "Turmeric", emoji: "🟡", category: "spice" },
  { id: "vanilla", name: "Vanilla", emoji: "🟤", category: "spice" },
  { id: "vinegar", name: "Vinegar", emoji: "🌾", category: "spice" },

  /* --- Drinks (30) --- */
  { id: "almond-milk-drink", name: "Almond milk", emoji: "🥛", category: "drink" },
  { id: "apple-juice", name: "Apple juice", emoji: "🍎", category: "drink" },
  { id: "bone-broth", name: "Bone broth", emoji: "🥣", category: "drink" },
  { id: "chamomile-tea", name: "Chamomile tea", emoji: "🍵", category: "drink" },
  { id: "chicken-broth", name: "Chicken broth", emoji: "🥣", category: "drink" },
  { id: "chocolate-milk", name: "Chocolate milk", emoji: "🥛", category: "drink" },
  { id: "coconut-water", name: "Coconut water", emoji: "🥥", category: "drink" },
  { id: "cranberry-juice", name: "Cranberry juice", emoji: "🔴", category: "drink" },
  { id: "fruit-smoothie", name: "Fruit smoothie", emoji: "🍓", category: "drink" },
  { id: "ginger-tea", name: "Ginger tea", emoji: "🍵", category: "drink" },
  { id: "grape-juice", name: "Grape juice", emoji: "🍇", category: "drink" },
  { id: "green-smoothie", name: "Green smoothie", emoji: "🥤", category: "drink" },
  { id: "green-tea", name: "Green tea", emoji: "🍵", category: "drink" },
  { id: "herbal-tea", name: "Herbal tea", emoji: "🍵", category: "drink" },
  { id: "hot-chocolate", name: "Hot chocolate", emoji: "☕", category: "drink" },
  { id: "juice-box", name: "Juice box", emoji: "🧃", category: "drink" },
  { id: "kefir-drink", name: "Kefir drink", emoji: "🥛", category: "drink" },
  { id: "kombucha", name: "Kombucha", emoji: "🍵", category: "drink" },
  { id: "lemonade", name: "Lemonade", emoji: "🍋", category: "drink" },
  { id: "milkshake", name: "Milkshake", emoji: "🥤", category: "drink" },
  { id: "oat-milk-drink", name: "Oat milk", emoji: "🥛", category: "drink" },
  { id: "orange-juice", name: "Orange juice", emoji: "🍊", category: "drink" },
  { id: "peppermint-tea", name: "Peppermint tea", emoji: "🍵", category: "drink" },
  { id: "smoothie", name: "Smoothie", emoji: "🥤", category: "drink" },
  { id: "soda", name: "Soda", emoji: "🥤", category: "drink" },
  { id: "sparkling-water", name: "Sparkling water", emoji: "💧", category: "drink" },
  { id: "sports-drink", name: "Sports drink", emoji: "🥤", category: "drink" },
  { id: "tomato-juice", name: "Tomato juice", emoji: "🍅", category: "drink" },
  { id: "vegetable-broth", name: "Vegetable broth", emoji: "🥣", category: "drink" },
  { id: "water", name: "Water", emoji: "💧", category: "drink" },
];

/* Threshold of ratings that unlocks the starter plan in the taste test
   (also drives the milestone copy variant on the progress strip). */
export const STARTER_PLAN_THRESHOLD = 30;

export const TODAYS_PLAN = [
  {
    time: "Breakfast · 8:00",
    name: "Banana oats with hidden spinach",
    emoji: "🥣",
    bg: "#F4E5C7",
    tags: [
      { label: "Iron+", tone: "sage" as const },
      { label: "Familiar", tone: "warm" as const },
    ],
    status: "done" as const,
  },
  {
    time: "Lunch · 12:30",
    name: "Roasted carrot ribbons + couscous",
    emoji: "🥗",
    bg: "#DCE8DD",
    tags: [
      { label: "Try new", tone: "sage" as const },
      { label: "Vit. A", tone: "berry" as const },
    ],
    status: "partial" as const,
  },
  {
    time: "Dinner · 18:00",
    name: "Tomato pasta with lentil sauce",
    emoji: "🍝",
    bg: "#F0DEE3",
    tags: [
      { label: "Iron+", tone: "sage" as const },
      { label: "Loved", tone: "warm" as const },
    ],
    status: "pending" as const,
  },
];

export type ChildProfile = {
  name: string;
  age: number;
  gender: "girl" | "boy" | "unspecified";
};

export const DEFAULT_CHILD: ChildProfile = {
  name: "Maya",
  age: 4,
  gender: "girl",
};
